---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Charon.
--- DateTime: 2022/8/17 10:28
---

print("hello lua")
--全局变量
num = 10
print("num="..num)
--局部变量
local name = false
--使用type获得数据类型
local myType = type(num)
local myName = type(name)
print("type="..myType)
print("type="..myName)
--if else
local age = 14
if age >=18 then print("成年人");
else
    print("未成年")
end

--for循环

for i = 0,5,2 do
    print("i = "..i);
end

--函数
function sum(n1,n2)
    return n1+n2
end
local result = sum(10,30)
print("result="..result)