server:
  port: 9100
# 网关配置
spring:
  application:
    name: test-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.245:8848
    gateway:
      routes:
      - id: position-server-route
        uri: lb://test-position-service
        predicates: #断言
        - Path=/position/list/**,/position/**
      - id: dept-server-route
        uri: lb://test-dept-service
        predicates: #断言
          - Path=/dept/list/**,/dept/**,/getAllDept/**,/getDeptById/**

      globalcors:
        cors-configurations: # 跨域配置
          '[/**]': # 匹配所有路径
            allowed-origins: # 允许的域名
              - "http://localhost:8080"
            allowed-headers: "*" # 允许的请求头
            allowed-methods: "*" # 允许的方法
            allow-credentials: true

user:
  white-list: # 白名单
    - /**



