#server:
#  port: 9999
## 网关配置
#spring:
#  application:
#    name: gateway-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.75.245:8848
#    gateway:
#      routes:
#      - id: promotion-server-route
#        uri: lb://promotion-service
#        predicates: #断言
#        - Path=/ad/list/**,/ad/promotionAd/**,/ad/upload/**
#
#      globalcors:
#        cors-configurations: # 跨域配置
#          '[/**]': # 匹配所有路径
#            allowed-origins: # 允许的域名
#              - "http://localhost:8081"
#            allowed-headers: "*" # 允许的请求头
#            allowed-methods: "*" # 允许的方法
#            allow-credentials: true
#
#user:
#  white-list: # 白名单
#    - /**


