#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/edu_user?serverTimezone=UTC&useUnicode=true
#    username: root
#    password: root
#  redis:
#    host: 192.168.75.245
#    port: 6379
#    database: 0
#    jedis:
#      pool:
#        max-active: 100
#        max-wait: 100ms
#        max-idle: 100
#        min-idle: 10
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#  type-aliases-package: com.charon.comment.entity
#  mapper-locations: classpath:mapper/*.xml
#
