server:
  port: 9999
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/

# 网关配置
spring:
  application:
    name: mysql-gateway-server
  cloud:
    gateway:
      routes:
      - id: order-server-route
        uri: lb://mysql-order-server  #服务名称
        predicates: #断言
        - Path=/orderlist/**,/order/**  #匹配路径

      - id: product-server-route
        uri: lb://mysql-product-server  #服务名称
        predicates: #断言
        - Path=/productlist/**,/product/**  #匹配路径

      - id: user-server-route
        uri: lb://mysql-user-service  #服务名称
        predicates: #断言
        - Path=/login,/logout,/user/**  #匹配路径

      globalcors:
        cors-configurations: # 跨域配置
          '[/**]': # 匹配所有路径
            allowed-origins: # 允许的域名
              - "http://localhost:8080"
            allowed-headers: "*" # 允许的请求头
            allowed-methods: "*" # 允许的方法
            allow-credentials: true # 是否携带cookie

user:
  white-list: # 白名单
    - /login
    - /logout