#server:
#  port: 7002
#  #网关配置
#spring:
#  application:
#    name: search-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.75.245:8848  # nacos的地址，端口默认是8848(注册)
#  elasticsearch:
#    uris: 192.168.75.245:9200

